name: CI

on:
  push:
  workflow_dispatch:

env:
  FORCE_COLOR: true
  NODE_VERSION: 20

jobs:
  setup:
    name: Lint Bot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run Linter
        run: bun run check

      #- name: Run Tests
      #  run: bun run coverage

      - name: Create Release
        if: success() && github.ref == 'refs/heads/develop'
        run: bun semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
