name: CI

on:
  push:
  workflow_dispatch:

env:
  FORCE_COLOR: true
  NODE_VERSION: 18

jobs:
  setup:
    name: Lint Bot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile # For some reason, pnpm install fails with a frozen lockfile

      - name: Run Linter
        run: pnpm lint

      - name: Run Tests
        run: pnpm coverage

      - name: Create Release
        if: success() && github.ref == 'refs/heads/develop'
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
