name: Inspector Zeep

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env:
  FORCE_COLOR: true
  NODE_VERSION: 20

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile # For some reason, pnpm install fails with a frozen lockfile

      - name: Setup SteamCMD
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Setup Hash Cache Name
        run: |
          string="${{ vars.ZEEPKIST_THEME_NAME }}"
          formattedString=$(echo "$string" | tr ' ' '-' | awk '{print tolower($0)}')

          echo "ZEEPKIST_THEME_HASH_PATH=./hash/${formattedString}.json" >> $GITHUB_ENV

      - run: cat ${{ env.ZEEPKIST_THEME_HASH_PATH }} || true

      - name: Restore Hash Cache
        uses: actions/cache@v3
        with:
          path: ./hash/${{ env.ZEEPKIST_THEME_HASH_PATH }}
          key: hashes-${{ hashFiles(env.ZEEPKIST_THEME_HASH_PATH) }}
          restore-keys: |
            hashes-

      - name: Validate Submissions
        run: pnpm run start
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_DISCUSSION_CHANNEL_ID: ${{ vars.DISCORD_DISCUSSION_CHANNEL_ID }}
          DISCORD_SUBMISSION_CHANNEL_ID: ${{ vars.DISCORD_SUBMISSION_CHANNEL_ID }}
          DISCORD_JUDGE_CHANNEL_ID: ${{ vars.DISCORD_JUDGE_CHANNEL_ID }}
          ZEEPKIST_THEME_NAME: ${{ vars.ZEEPKIST_THEME_NAME }}
          STEAMCMD_PATH: ${{ vars.STEAMCMD_PATH }}
