name: Inspector Zeep

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # Every 30 minutes

env:
  FORCE_COLOR: true
  NODE_VERSION: 24

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup SteamCMD
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      #- name: Setup SteamCMD
      #  uses: CyberAndrii/setup-steamcmd@v1

      - name: Setup Hash Cache Name
        run: |
          string="${{ vars.ZEEPKIST_THEME_NAME }}"
          formattedString=$(echo "$string" | tr ' ' '-' | awk '{print tolower($0)}')

          echo "ZEEPKIST_THEME_HASH_PATH=./hash/${formattedString}.json" >> $GITHUB_ENV

      #- name: Inspect Hash Cache
      #  run: cat ${{ env.ZEEPKIST_THEME_HASH_PATH }} || true

      - name: Validate Submissions
        run: bun run start
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_DISCUSSION_CHANNEL_ID: ${{ vars.DISCORD_DISCUSSION_CHANNEL_ID }}
          DISCORD_SUBMISSION_CHANNEL_ID: ${{ vars.DISCORD_SUBMISSION_CHANNEL_ID }}
          DISCORD_JUDGE_CHANNEL_ID: ${{ vars.DISCORD_JUDGE_CHANNEL_ID }}
          ZEEPKIST_THEME_NAME: ${{ vars.ZEEPKIST_THEME_NAME }}
          STEAMCMD_PATH: ${{ vars.STEAMCMD_PATH }}

      - name: Upload Downloads Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v5
        with:
          name: downloads
          path: downloads


      - name: Commit Hash Cache
        if: ${{ success() }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ env.ZEEPKIST_THEME_HASH_PATH }} -f
          git diff-index --quiet HEAD || git commit -m "ci: update cache for ${{ vars.ZEEPKIST_THEME_NAME }} [skip ci]" && git push
